In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv(r"C:\Users\System -02\Downloads\Excel clean_02_hotel_bookings.csv")
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")
df.drop_duplicates
df.head(2)

,booking_id,hotel_name,hotel_type,arrival_date,nights_stayed,room_type,adults,children,booking_channel,lead_time_days,adr_per_night_inr,total_revenue_inr,cancellation_status,country_of_guest,special_requests,meal_plan
0,BKG628975,Taj Mahal Palace Mumbai,4-Star,1/1/2022,10,Family Room,1,0.0,Travel Agent,102,17411,174110,No,UAE,2.0,Full Board
1,BKG496103,Treebo Trend City Inn,4-Star,1/1/2022,3,Family Room,1,0.0,Booking.com,348,2029,6087,Yes,India,2.0,Breakfast Only

In [3]:
df.isnull().sum().sort_values(ascending=False).head(5)

meal_plan           385
children            384
country_of_guest    384
special_requests    384
booking_id            0
dtype: int64

In [4]:
df[['meal_plan','children','country_of_guest','special_requests']].head(2)

        meal_plan  children country_of_guest  special_requests
0      Full Board       0.0              UAE               2.0
1  Breakfast Only       0.0            India               2.0

In [5]:
for col in['meal_plan','country_of_guest']:
    df[col] = df[col].fillna(df[col].mode()[0])
    
for co in ['children','special_requests']:
    df[co]= df[co].fillna(df[co].median())

In [6]:
df.isnull().sum()

booking_id             0
hotel_name             0
hotel_type             0
arrival_date           0
nights_stayed          0
room_type              0
adults                 0
children               0
booking_channel        0
lead_time_days         0
adr_per_night_inr      0
total_revenue_inr      0
cancellation_status    0
country_of_guest       0
special_requests       0
meal_plan              0
dtype: int64

In [7]:
df.iloc[50:55]

,booking_id,hotel_name,hotel_type,arrival_date,nights_stayed,room_type,adults,children,booking_channel,lead_time_days,adr_per_night_inr,total_revenue_inr,cancellation_status,country_of_guest,special_requests,meal_plan
50,BKG732669,Courtyard by Marriott,3-Star,15/01/2022,7,Suite,3,2.0,Walk-in,13,11148,78036,No,India,2.0,Full Board
51,BKG375756,Park Inn by Radisson,5-Star,1/15/2022,4,Double Room,2,1.0,Agoda,241,3954,15816,No,Singapore,3.0,Breakfast Only
52,BKG963105,Hilton Garden Inn,4-Star,15-01-2022,3,Suite,1,0.0,corporate,264,6780,20340,No,India,0.0,BB
53,BKG688747,The Leela Goa,3-Star,16/01/2022,9,Deluxe,3,0.0,Corporate Booking,345,17436,156924,Yes,France,3.0,Full Board
54,BKG912236,Park Inn by Radisson,Resort,1/16/2022,11,Twin Room,2,1.0,Travel Agent,52,5977,65747,Yes,USA,3.0,Full Board

In [8]:
df['arrival_date'] = pd.to_datetime(df['arrival_date'],dayfirst=True,errors='coerce')

In [9]:
df['children'] = df['children'].astype(int)

In [10]:
df.head(5)

,booking_id,hotel_name,hotel_type,arrival_date,nights_stayed,room_type,adults,children,booking_channel,lead_time_days,adr_per_night_inr,total_revenue_inr,cancellation_status,country_of_guest,special_requests,meal_plan
0,BKG628975,Taj Mahal Palace Mumbai,4-Star,2022-01-01,10,Family Room,1,0,Travel Agent,102,17411,174110,No,UAE,2.0,Full Board
1,BKG496103,Treebo Trend City Inn,4-Star,2022-01-01,3,Family Room,1,0,Booking.com,348,2029,6087,Yes,India,2.0,Breakfast Only
2,BKG234115,Radisson Blu Pune,3-Star,2022-01-01,9,Super Deluxe,3,2,corporate,270,6307,56763,Yes,Nepal,0.0,CP
3,BKG511231,Hyatt Regency Chennai,Resort,2022-01-01,3,Super Deluxe,2,1,Booking.com,106,28565,85695,No,Sri Lanka,0.0,CP
4,BKG379933,Lemon Tree Lucknow,4-Star,2022-01-02,6,Presidential Suite,2,0,Travel Agent,71,1902,11412,No,India,1.0,AP

In [11]:
df.dtypes

booking_id                        str
hotel_name                        str
hotel_type                        str
arrival_date           datetime64[us]
nights_stayed                   int64
room_type                         str
adults                          int64
children                        int64
booking_channel                   str
lead_time_days                  int64
adr_per_night_inr               int64
total_revenue_inr               int64
cancellation_status               str
country_of_guest                  str
special_requests              float64
meal_plan                         str
dtype: object

In [12]:
for i in ['hotel_name','room_type','booking_channel','country_of_guest','cancellation_status']:
    df[i] = df[i].str.title()

In [16]:
df.isnull().sum().sort_values(ascending=False).head(4)

arrival_date    1543
booking_id         0
hotel_name         0
hotel_type         0
dtype: int64

In [17]:
df['arrival_date'] = df['arrival_date'].ffill()

In [18]:
df.isnull().sum().head(5)

booking_id       0
hotel_name       0
hotel_type       0
arrival_date     0
nights_stayed    0
dtype: int64

In [20]:
from sqlalchemy import create_engine
username ="postgres"
password = "nikku2004" 
port = "5432"
host= "localhost"
database = "hotel"
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
df.to_sql("hotel",engine,if_exists="replace",index= False)

830